export const GET_JOBS = 'GET_JOBS';
export const GET_JOBS_REQUESTED = 'GET_JOBS_REQUESTED';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';
export const GET_JOBS_FAILED = 'GET_JOBS_FAILED';
export const UPDATE_PARAMS = 'UPDATE_PARAMS';
export const GET_JOB_BY_ID = 'GET_JOB_BY_ID';
